services:
  server:
    image: yourdockerhubusername/code-coalition-server:latest
    container_name: code-coalition-server
    networks:
      - Code-Coalition
    ports:
      - "3000:3000"

  client:
    image: yourdockerhubusername/code-coalition-client:latest
    container_name: code-coalition-client
    networks:
      - Code-Coalition
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  Code-Coalition:
    driver: bridge
